{
 "title": "Online Boutique Energy consumption",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "exe",
    "label": "Service",
    "query": "cartservice,checkoutservice,shippingservice,locust"
   }
  ]
 },
 "panels": [
  {
   "title": "Online boutique consumption",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "scaph_process_power_consumption_microwatts{exe=~\"cartservice|checkoutservice|shippingservice|locust|java|server\"} / 1000000",
     "legendFormat": "{{exe}}"
    }
   ]
  },
  {
   "title": "3h online boutique energy consumption",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum_over_time(avg_over_time(avg(sum(scaph_process_power_consumption_microwatts{exe=~\"cartservice|checkoutservice|shippingservice|locust|java|server\"}) * 1.4)[1h:1h])[3h:1h]) /1000000",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "3h online boutique CO2 eq",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "gCO₂eq" } },
   "targets": [
    {
     "expr": "sum_over_time(avg_over_time(avg(sum(scaph_process_power_consumption_microwatts{exe=~\"cartservice|checkoutservice|shippingservice|locust|java|server\"}) * 1.4 * \n      ignoring(cmdline, container, endpoint, exe, instance, job, namespace, pid, pod, service) carbon_intensity_fr \n      / 1000)[1h:1h])[3h:1h]) /1000000",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "A week online boutique CO2 eq",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 5, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "gCO₂eq" } },
   "targets": [
    {
     "expr": "sum_over_time(avg_over_time(avg(sum(scaph_process_power_consumption_microwatts{exe=~\"cartservice|checkoutservice|shippingservice|locust|java|server\"}) * 1.4 * \n      ignoring(cmdline, container, endpoint, exe, instance, job, namespace, pid, pod, service) carbon_intensity_fr \n      / 1000)[1h:1h])[3h:1h]) /1000000 * 8 * 7",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "$exe",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "$exe consumption",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "scaph_process_power_consumption_microwatts{exe=~\"$exe\"} / 1000000",
       "legendFormat": "{{exe}}"
      }
     ]
    },
    {
     "title": "3h $exe energy consumption",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 5, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "expr": "sum_over_time(avg_over_time(avg(scaph_process_power_consumption_microwatts{exe=\"$exe\"} * 1.4)[1h:1h])[3h:1h]) /1000000",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "3h $exe CO2 eq",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 5, "x": 17, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "gCO₂eq" } },
     "targets": [
      {
       "expr": "sum_over_time(avg_over_time(avg(scaph_process_power_consumption_microwatts{exe=\"$exe\"} * 1.4 * \n      ignoring(cmdline, container, endpoint, exe, instance, job, namespace, pid, pod, service) carbon_intensity_fr \n      / 1000)[1h:1h])[3h:1h]) /1000000",
       "legendFormat": "Value"
      }
     ]
    }
   ]
  },
  {
   "title": "Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host consumption",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "scaph_host_power_microwatts / 1000000",
       "legendFormat": "Host"
      }
     ]
    },
    {
     "title": "3h host energy consumption",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 5, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "expr": "sum_over_time(avg_over_time(avg(scaph_host_power_microwatts * 1.4)[1h:1h])[3h:1h]) /1000000",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "3h host CO2 eq",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 5, "x": 17, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "gCO₂eq" } },
     "targets": [
      {
       "expr": "sum_over_time(avg_over_time(avg(scaph_host_power_microwatts * 1.4 * \n      ignoring(instance, container, endpoint, job, namespace, pod, service) carbon_intensity_fr \n      / 1000)[1h:1h])[3h:1h]) /1000000",
       "legendFormat": "Value"
      }
     ]
    }
   ]
  }
 ]
}