apiVersion: v1
kind: Pod
metadata:
  name: electricitymap
  namespace: observability
  labels:
    app: electricitymap
spec:
  containers:
  - name: electricitymap-container
    image: airklizz/electricitymap_exporter:latest
    ports:
    - name: metrics
      containerPort: 8000
    env:
    - name: AUTH_TOKEN
      valueFrom:
        secretKeyRef:
          name: electricitymap-exporter-secret
          key: AUTH_TOKEN

---

apiVersion: v1
kind: Service
metadata:
  name: electricitymap-service
  namespace: observability
  labels:
    app: electricitymap
spec:
  selector:
    app: electricitymap
  ports:
    - name: metrics
      port: 8000
      targetPort: metrics
  type: ClusterIP

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: electricitymap-service-monitoring
  namespace: observability
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - path: /metrics
      port: metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 30s
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: electricitymap